.pep8speaks.yml
neurodsp/shape/cyclefeatures.py

scipy.signal.hilbert takes a long time for some seemingly arbitrary signal lengths. A way around this is to specify the number of points in the signal. This was not initially supported in the `shape` module, like it is in the `timefrequency` module.

adapt cycle by cycle amplitude estimate for possible slow hilbert transform

---

neurodsp/sim.py

Optional outputs were missing from the ‘return’ segment of the docstring.
Also, there was a bug in returning some of these optional inputs together.

Update docstring for optional output to simulating bursty oscillator

---

neurodsp/sim.py
neurodsp/spectral.py
neurodsp/tests/test_spectral.py

in spectral.psd():
- added flim option to return truncated psd
- added spg_outlierpct option to through out a percentage of spectrogram slices prior to averaging.
in spectral.rotate_powerlaw():
- check for whether f_axis[0] is 0Hz before defaulting to unity
- check that f_rotation is in range of f_axis

truncated and outlier removed spectral.psd, value checking in spectral.rotate_powerlaw

---

neurodsp/spectral.py

typo causes compute_spectrum to crash when an outlier_pct is specified

fixed typo in spectral.compute_spectrum

---

neurodsp/filt.py
neurodsp/spectral.py
neurodsp/timefrequency.py

Non API breaking refactors and clean ups of the spectral & time frequency module. (Somewhat related to #140 - but nothing that breaks anything here). 
Main changes:
- Split up sub-function for settings checking, discarding outliers and sub-selecting from spectra
- Split out the different compute spectrum methods
- Get time frequency to borrow & use the utility functions that were split out in `filter` (get rid of duplicated code within `timefrequency`, and across the package. This includes moving & renaming a 'infer_passtype' from tf -> filt. 
Notably, this fixes a bug in which the old version would fail out if you tried to discard outliers in compute_spectrum with a 1d signal.

Updates to Spectral & TimeFrequency

---

doc/conf.py
examples/plot_mne_example.py

This is a draft of an example for using NDSP together with MNE, related to a suggestion on the JOSS review, and as mentioned in #143 
The broad outline is straightforward (grab the MNE sample data, and start messing with it), but I realized it's not so obvious what to do / show in this example. 
So far this is a fairly trivial example of extracting a channel of interest, and checking for bursts. 
The main thing we would want to show, though, is using NDSP + MNE across multiple channels, and probably in an event related manner, and focusing on custom and interesting NDSP specialties (not showing things that MNE already does well, such as filtering). 
So, what quick & straightforward analyses with NDSP would be most useful / interesting to show with an MNE organization / dataset? Ideally a …

Add example using with MNE

---

doc/glossary.rst

Related to #138 - this is place for us to broadly work on and discuss a potential glossary. 
So far I just added a sphinx style glossary file, and a really quick scan collecting some terms that could potentially go into it. 
The idea is that we can somewhat crowdsource this glossary - so if you have a suggested term or definition - throw it here! In terms of scope, this glossary should be fairly light on the level of detail, offering just a quick definition, but link out to as many resources as we can find to help find and scaffold support for DSP and it's neuroscience applications.

Add glossary

---

paper/paper.md

With the upcoming 2.0 release, there are some slight re-organizations to the codebase. This PR updates the JOSS paper a little to both reflect the upcoming changes, and to make it more open-ended for future development (basically - talk about things that are included, so it doesn't fall out of date if things get extended later).

Update paper to reflect 2.0 orgs

---

neurodsp/burst/dualthresh.py
neurodsp/burst/utils.py
neurodsp/filt/checks.py
neurodsp/filt/filter.py
neurodsp/filt/fir.py
neurodsp/filt/iir.py
neurodsp/filt/utils.py
neurodsp/plts/__init__.py
neurodsp/plts/filt.py
neurodsp/plts/rhythm.py
neurodsp/plts/spectral.py
neurodsp/plts/time_series.py
neurodsp/rhythm/lc.py
neurodsp/rhythm/swm.py
neurodsp/sim/aperiodic.py
neurodsp/sim/combined.py
neurodsp/sim/periodic.py
neurodsp/sim/transients.py
neurodsp/spectral/power.py
neurodsp/spectral/utils.py
neurodsp/spectral/variance.py
neurodsp/timefrequency/hilbert.py
neurodsp/timefrequency/wavelets.py
neurodsp/utils/decorators.py
summary.sh

Related to #180. All functions with API docs now have examples in the docstrings. All doctests pass. Running doctest has been added to summary.sh. A few docstring typos have been fixed with this PR as well.

[DOC] examples added to docstrings

---

neurodsp/plts/settings.py
neurodsp/plts/spectral.py
neurodsp/plts/style.py
neurodsp/plts/time_series.py
neurodsp/tests/test_plts_rhythm.py
neurodsp/tests/test_plts_spectral.py
neurodsp/tests/test_plts_style.py
neurodsp/tests/test_plts_time_series.py
neurodsp/tests/test_plts_utils.py

Before,  'alpha' and 'lw' had no effect when plotting with `plot_time_series`, and this PR fixes this. A list can be passed for either line style argument, and the style will be applied to each line in the corresponding order. For example, in `plot_time_series(times, [sig_a, sig_b], lw=[1, 5])`, a linewidth of 1 will be applied to sig_a and a width of 5 for sig_b. Alternatively a single value can be passed and all lines will have the same style.
Here is a [notebook](https://github.com/ryanhammonds/neurodsp/blob/explores/line_styles.ipynb) that has an example of the change.

[FIX] Allow line styles when plotting.

---

neurodsp/plts/time_series.py

This changes the color default in `plot_time_series` to 'k' and 'r' for 1 or 2 signals. If more than two signals are given, then mpl's default color cycle is used. Users can still overwrite these defaults.

[ENH] Color cycling defaults

---

neurodsp/plts/settings.py
neurodsp/plts/style.py

This PR extends application of line styling to allow it to include `marker` and `markersize` (1st commit). 
Relatedly, `plot_style` approach is updated to only apply line style to lines added to the plot in the current plot call (3rd commit).
The reason for the update to line style application is that the old approach would apply single style args to all lines even if they came from different plot calls. For example, in the old approach, in the following call both lines would be made dashed, which I think is unexpected / not ideal:
```
fig, ax = plt.subplots(figsize=(15, 3))
plot_time_series(times, sig1, lw=6, ax=ax)
plot_time_series(times, sig2, linestyle='--', ax=ax)
```
With the update, a line styling will only get applied to the line or lines from the plot call from which the styling …

Extend to new line styling, and update application

---

neurodsp/filt/checks.py
neurodsp/filt/fir.py
neurodsp/filt/iir.py
neurodsp/filt/utils.py
neurodsp/tests/test_filt_checks.py
neurodsp/tests/test_filt_fir.py
neurodsp/tests/test_filt_iir.py
neurodsp/tests/test_filt_utils.py

This PR addresses issue #193 for the filt submodule. Specifically, the following modifications have been made:
1. Update function call in fir.py for firwin(). We now feed in the sampling rate directly, rather than feeding in the deprecated argument nyq, or the nyquist frequency.
2. Previously a warning was raised if you asked for a IIR butterworth filter that was anything but a bandpass. That warning has now been removed.
3. Most importantly, I made changes to how IIR filters are now computed. Instead of computing a and b coefficients of the transfer function, we now compute the second order series expansion. This addresses numerical instabilities for butterworth filters of higher orders. I did not want to change any of the checks or utils for FIR filters, so I created new functions for …

[BUG] - Fix numerical instabilities for IIR filters

---

neurodsp/spectral/power.py
neurodsp/timefrequency/hilbert.py
neurodsp/timefrequency/wavelets.py

This PR addresses the concerns raised in issue #193 for the time frequency analysis submodule, as well as the semantic issue  raised in issue #196. Specifically,
1. `compute_wavelet_transform` now has `norm` as a kwarg to specify what normalization to use. It defaults to `sss`, or the L2 norm. Moreover, the output has been transposed so that frequency is plotted on the y-axis, and time on the x-axis. This matches convention for wavelet transforms in other packages.
2. Update the test for `compute_wavelet_transform` to average across the appropriate axis.
3. We now wrap the instantaneous phase vector using `np.unwrap` inside the call of `freq_by_time`. 
4. Update the docstring for `robust_hilbert` to reflect that the return value is the analytic signal, not the hilbert transform.

[BUG] - Technical Audit: Time Frequency edits

---

doc/api.rst
neurodsp/spectral/__init__.py
neurodsp/spectral/utils.py
neurodsp/tests/test_spectral_utils.py

This PR adds `trim_spectrogram` which allows a user to trim particular frequency and time values from a spectrogram.

[ENH] - Spectral: Trim Spectrogram

---

neurodsp/tests/conftest.py
neurodsp/tests/settings.py
neurodsp/tests/test_filt_filter.py
neurodsp/tests/test_filt_fir.py
neurodsp/tests/test_spectral_power.py
neurodsp/tests/test_timefrequency_hilbert.py

This PR adds accuracy checks (#194)  for
1. All hilbert.py related functions using a simple sinusoid.
2. FIR filtering of a low-frequency sinusoid. Specifically, it checks that it is attenuated under a high pass filter, and is minimally attenuated under a lowpass filter.
3. `compute_spectrum` with the `medfilt` and `welch` options. It uses a low frequency sinusoid to compare against where the power spectrum should be a dirac spike at frequency 1 and zero elsewhere.

[ENH] - Tech Audit #2: Accuracy checks for Hilbert Transform, Filters, and Spectra

---

neurodsp/sim/periodic.py
neurodsp/tests/utils/test_norm.py
neurodsp/utils/decorators.py
neurodsp/utils/norm.py

This PR drops the option in the normalization to only apply transforms to non-zero. This approach, designed to be able to normalize burst regions (ignoring surrounding zeros) turned out to be a bad idea, because there can be other zeros. This created some 'discontinuities' (issue noted in #174). In order to be able to normalize burst signals, without normalizing to non-burst regions, this PR also updates how normalizations get applied in `sim_burst_normalization`, applying them to the simulated signal before tiling. 
Note that this PR replaces #189, which was a wrong-headed fix, that tried to do resampling. 
Review Notes:
@ryanhammonds : if you can review this one, keep in mind it supercedes & adopts from #189, so you can review in light of what you did for that PR. 
@elybrand : since …

[BUG] - Fix the sims normalizations

---

neurodsp/tests/timefrequency/test_hilbert.py
neurodsp/timefrequency/hilbert.py

This is in response to #214, `hilbert_increase_n` and `increase_n` arguments have been removed and tests are updated.

[FIX] Deprecated hilbert_increase_n arg

---

doc/api.rst
neurodsp/aperiodic/__init__.py
neurodsp/aperiodic/irasa.py
neurodsp/tests/aperiodic/test_irasa.py
neurodsp/tests/conftest.py
neurodsp/tests/settings.py

Add an implementation of IRASA. 
Note - this implementation is inspired by / draws from the one in YASA:
https://github.com/raphaelvallat/yasa/blob/master/yasa/spectral.py#L326
Reviews / ToDos:
- @elybrand : if you feel like you have a sense of IRASA, can you check the implementation for technical sound-ness?
-  also, I wanted to add the implementation so you can play with it. Feel free to 'explore' it for a while before proper reviewing
- @ryanhammonds : can you check the code elements & double check it is well organized to fit into NDSP
- so far, there are no tests, so if you could add some code tests that would be great!
- @rdgao : tagging you in since you've played with IRASA a bit - but nothing in particular needed!
- thought you might be interested in checking it out / sanity …

[ENH] - Add IRASA

---

doc/api.rst
neurodsp/aperiodic/__init__.py
neurodsp/aperiodic/autocorr.py
neurodsp/tests/aperiodic/test_autocorr.py

Add a function to compute autocorrelation of time series. 
Note: this implementation was shamelessly taken and adapted from @rdgao's implementation. I'm suggesting we add this functionality, for a stable implementation, including for use in the AperiodicMethods project. Does that sound good to use @rdgao?
For reviewing, the usual: @elybrand please check if the math works / makes sense, and @ryanhammonds please sanity check the code, tests, etc.

[ENH] - Add autocorrelation measure

---

neurodsp/burst/utils.py
neurodsp/tests/burst/test_utils.py

[BUG] Fix detection of burst on- and offsets.

---

neurodsp/sim/__init__.py
neurodsp/sim/combined.py
neurodsp/tests/sim/test_combined.py

This PR builds a new combined aperiodic and periodic simulation which allows the user to simulate an aperiodic component with a specified power law exponent and a single oscillatory component with specified central frequency, bandwidth, and relative height above the aperiodic component in the log-power spectrum. 
Here is a minimal working example with the analytical power spectrum superimposed for comparison.
```python
from neurodsp.utils.data import create_times
from neurodsp.plts import plot_power_spectra, plot_time_series
from neurodsp.sim import sim_central_freq
from neurodsp.spectral import compute_spectrum
np.random.seed(0)
n_seconds = 10
fs = 10**3
chi = -2
central_freq = 20
bw = 5
ht = 2
sig = sim_central_freq(n_seconds, fs, chi, …
```

[ENH] - Simulation of Central Frequency in the Time Domain

---

neurodsp/sim/__init__.py
neurodsp/sim/aperiodic.py
neurodsp/tests/settings.py
neurodsp/tests/sim/test_aperiodic.py

This simulation builds a time series out of sums of sinusoids whose power spectrum follows the Lorentzian law
P(f) = 1/(f^chi1 * (f^chi2 + k).
Below is a minimal working example.
```python
from neurodsp.plts import plot_time_series, plot_power_spectra
from neurodsp.utils.data import create_times
from neurodsp.spectral import compute_spectrum
from neurodsp.sim import sim_knee
n_seconds = 10
fs = 10**3
sig_len=n_seconds*fs
chi1 = 1
chi2= 2
k = 10**2
times = create_times(n_seconds, fs)
sig = sim_knee(n_seconds, fs, chi1, chi2, k)
freqs, psd = compute_spectrum(sig, fs)
freqs, psd = freqs[1:], psd[1:]
psd_baseline = np.array([1/(f**chi1*(f**chi2 + k)) for f in freqs])
psd_baseline *= psd[0]/psd_baseline[0]
fig, axes = plt.subplots(2,1, …
```

[ENH] - Simulate time series with knees, sum of sinusoids

---

neurodsp/tests/sim/test_aperiodic.py

Related to #236. The original test used `n_seconds=1` and `fs=100`, while specifying a knee at 100hz. This lead to unstable estimates of the post knee slope (causing it's accuracy test to fail) - since the max freq that could be returned from `compute_spectrum` was 50hz. Tests would randomly pass/fail depending on seed. Increasing `n_seconds` to 10 and `fs` to 1000 fixed the issue.

[BUG] Fix sim_knee accuracy test

---

CONTRIBUTING.md

I think it might be helpful to explain how to build the documentation during development.

[MRG, DOC] Add message about how to build the documentation

---

neurodsp/tests/sim/test_aperiodic.py

This is a follow up on #237, to fix up that update to make sure that the tests are consistent in using the same sampling rate for simulating the data as for computing the power spectrum. 
@ryanhammonds - this should be pretty procedural. Assuming this looks good to you on a quick glance, should be able to be merged in.

[FIX] - Update settings for knee test

---

neurodsp/sim/cycles.py
neurodsp/sim/periodic.py
neurodsp/tests/sim/test_cycles.py
neurodsp/tests/sim/test_periodic.py
neurodsp/tests/utils/test_data.py
neurodsp/utils/data.py

This update extends the available approaches for simulating bursty oscillations.
Main updates:
- add a new approach for simulating bursts, by specifying burst lengths and inter-burst intervals
- refactor the burst code, to allow for more customizable 
- fixes to standardize that all sims of the same length get the same amount of samples, & other small fixes
Notes
- I'm not totally sure about the API here. It's currently set up in a transition state, to not change prior behaviour, while adding in the new approaches to the same burst function. Thoughts on this?
- There are a couple little things to try and anticipate more customizability, for example the 'durations' approach is set up to eventually be able to take in generator objects to sample variable parameters, but this isn't totally …

[ENH] - Update approach for simulating bursts

---

neurodsp/plts/time_series.py
neurodsp/tests/plts/test_time_series.py

This updates `plot_time_series` to accept 2d arrays, in addition to a list of 1d arrays. Before this would not work:
```python
from neurodsp.plts import plot_time_series
n_sigs = 10
fs = 1000
n_seconds = 10
sigs = np.repeat(np.arange(n_sigs), int(n_seconds * fs))
sigs = sigs.reshape((n_sigs, int(n_seconds * fs)))
times = np.arange(0, len(sigs[0])/fs, 1/fs)
plot_time_series(times, sigs)
```
and it would require:
```python
plot_time_series(times, list(sigs))
```

[ENH] 2d Array Plotting

---

neurodsp/sim/cycles.py
neurodsp/sim/periodic.py

This update allows for passing in a callable to `sim_cycle`. 
This is to make it easier to explore new cycle types. In particular, this means a callable can be passed through from `sim_oscillation`. I think this useful to be able to be able to explore and test new cycles and tiling, without having to add them to the module. If the function is well formed as a cycle function, it gets called, with any passed in parameters. 
Consider the following example that will now work:
```
from neurodsp.sim import sim_oscillation
def sim_offset_sine(n_seconds, fs, offset):
cycle = np.sin(2 * np.pi * 1 / n_seconds * (np.arange(int(fs * n_seconds)) / fs))
cycle = cycle + offset
return cycle
n_seconds, fs, freq = 1, 1000, 10
osc = sim_oscillation(n_seconds, fs, freq, sim_offset_sine, offset=1, mean=None) …
```

[ENH] - Add support for passing in a callable to sim_cycle

---

neurodsp/sim/cycles.py
neurodsp/sim/periodic.py
neurodsp/tests/sim/test_cycles.py
neurodsp/tests/utils/test_checks.py
neurodsp/utils/checks.py

This expands phase shifting to allow for minima-to-minima and maxima-to-maxima sims. It also add phase shifting to `sim_bursty_oscillation`, which wasn't possible before. The `phase` kwarg was added to `sim_cycle` so phase shifting could be done before tiling.
The motivation for this was working with sims + bycycle and the lack of a convenient way to sim cycles from trough-to-trough or peak-to-peak. When simulating from zerox-to-zerox, but bycycle defined cycles otherwise, cyclepoints could get messy. Maybe bycycle could be updated to define cycles from zerox-to-zerox, but that will likely have other side-effects to work out.
The `phase` argument still accepts a float from [0, 1], but it also accepts ``min`` or ``max`` strings to automatically determine the phase shift required to sim …

[ENH] Min-to-min and max-to-max phase shifting

---

neurodsp/aperiodic/dfa.py

I noticed a deprecation warning that `scipy.cumsum` is being deprecated, and will be removed in scipy 2.0 - so this updates to use cumsum from numpy instead, as recommended by the scipy deprecation. The results should be identical between the two functions, AFAIK.

[MNT] - Use cumsum from numpy instead of scipy

---

neurodsp/sim/aperiodic.py
neurodsp/sim/cycles.py
neurodsp/sim/periodic.py
neurodsp/tests/settings.py
neurodsp/tests/sim/test_cycles.py
neurodsp/tests/sim/test_periodic.py
neurodsp/tests/tutils.py
neurodsp/tests/utils/test_data.py
neurodsp/utils/data.py

This is an update to the convention for calculating the expected number of samples for a simulation, updating to round up, rather than down. 
This, in part, reverts a prior update that tried to consolidate on rounding down:
https://github.com/neurodsp-tools/neurodsp/commit/1439d48959d54abc7b598ab808ca45267885603e#diff-0c31582faa78b9253161cdc956a8ac5ba1da385c1411116af3c7861315e56b7c
The original reason for the update was that sometimes the simulated signal, and simulated time vector could end up different lengths (since we weren't super consistent on computing the expected number of cycles). When consolidating, I set to round down. However, that had an unexpected (and uncaught by the prior tests) that some sim'd signals could be shorter than expected. 
For example, on main right now, this …

[BUG] - Update standard for compute n_samples for simulations

---

neurodsp/sim/periodic.py

There was a bug in `sim_bursty_oscillation`, due to defining an empty dictionary in the function definition, which turns out to be quite bad (ooops, my bad). Because we dynamically update the dictionary in the function, this updates the default value, leading to issues. 
Here's an isolated example of the issue:
```
def test_dict_issue(var={}):
if not var:
var['new'] = 'value'
print(test_dict_issue.__defaults__)
test_dict_issue()
print(test_dict_issue.__defaults__)
```
Which gives this output
```
({},)
({'new': 'value'},)
```
Basically, giving an empty dictionary as default, and then updating this object updates the object linked in the function definition. Once I tracked this down - it's a simple fix, but it's a bit of a funky bug. 
Anyways, interesting / weird Python quick. I sorta knew …

[BUG] - Fix bug in `sim_bursty_oscillation`

---

neurodsp/plts/time_series.py
neurodsp/sim/aperiodic.py
neurodsp/tests/aperiodic/test_dfa.py
neurodsp/tests/aperiodic/test_irasa.py
neurodsp/tests/conftest.py
neurodsp/tests/filt/test_filter.py
neurodsp/tests/plts/test_filt.py
neurodsp/tests/plts/test_rhythm.py
neurodsp/tests/plts/test_spectral.py
neurodsp/tests/plts/test_time_series.py
neurodsp/tests/settings.py
neurodsp/tests/sim/test_aperiodic.py
neurodsp/tests/sim/test_cycles.py
neurodsp/tests/spectral/test_power.py
neurodsp/tests/timefrequency/test_hilbert.py
neurodsp/tests/utils/test_data.py

This started as a quick bug fix for a plot thing, and then escalated a little....
Updates in this PR:
- Bug fix: fixes labelling on a phase instantaneous frequency so it plays more nicely with subplots
- Makes test plots more realistic, so that saved out plots are more representative and easier to check
- Simplifies test settings and fixtures**
**We were starting to get a slightly unwieldy collection of settings and fixtures. As I was trying to generalize the plots, using more realistic signals, it became clear the mapping between test signals and settings was not super clear. So, a quick clean up which basically simplifies test signals to have one regime of (N_SECONDS, FS) for fixtures defined in conftest, and then makes any tests that need idiosyncratic custom test object definitions …

[MNT] - Update tests & small plot bug fixes

---

neurodsp/sim/__init__.py
neurodsp/sim/combined.py
neurodsp/sim/periodic.py
neurodsp/tests/sim/test_periodic.py

This allows the frequency and/or simulation kwarg(s) to vary on a cycle-by-cycle basis.
```python
from neurodsp.sim import sim_variable_oscillation
from neurodsp.plts import plot_time_series
fs = 1000
freqs = [ 5, 10, 15, 20]
rdsyms= [.2, .4, .6, .8]
sig = sim_variable_oscillation(fs, freqs, cycle='asine', rdsym=rdsyms)
times = np.arange(0, len(sig)/fs, 1/fs)
plot_time_series(times, sig)
```

[ENH] Simulate variable oscillations

---

neurodsp/sim/cycles.py
neurodsp/tests/sim/test_cycles.py

This update adds support for creating an asymmetric cycle with only one asymmetric extrema, to `sim_asine_cycle`.
For example, this code:
```
from neurodsp.sim.cycles import sim_asine_cycle
fs, freq = 1000, 10
cycle = sim_asine_cycle(1/freq, fs, 0.25, 'peak')
plt.plot(cycle)
```
Would now work, to have a 'peak-only asymmetric cycle', and gives this:
As a limitation of this - it seems unideal that there is an abrupt shift from the asymmetric to symmetric regime at the zero crossing point (ideally this might be smoother), but broadly I think this should be _okay_, and this update can still be useful for some things. 
Edit: I've been playing around with those code for awhile, including poking at different ways to do the offsets, and if there's a way to …

[ENH] - Add one sided asymmetric option to asine cycle

---

neurodsp/plts/utils.py
neurodsp/tests/plts/test_utils.py

This updates the `savefig` decorator to default to saving a figure when a file name is given, meaning `save_fig` does not have to be explicitly passed. The `save_fig` input can still be explicitly passed to stop the figure from saving. 
Following this update, this will now save:
`example_plot(file_path=TEST_PLOTS_PATH, file_name='test_savefig1.pdf')`
This will now not save:
`example_plot(save_fig=False, file_path=TEST_PLOTS_PATH, file_name='test_savefig3.pdf')`
^This might seem like a slightly weird construct, but it's something I use a fair amount - to define the name I need, but use a general setting to define when I actually save things.
This PR also updates the tests, generalizing them to check this new behaviour. It also moves away from using tempfile for these particular files, …

[ENH] - Update default for savefig

---

neurodsp/plts/utils.py
neurodsp/tests/plts/test_utils.py

I realized the `savefig` implementation that's in LISC seemed to usefully support a couple extra options in the `savefig`, that seemed quite useful. This extends the decorator in NDSP, to allow for setting to save out and close the plot (useful in scripts or loops), and also to allow for passing through kwargs.

[ENH] - Extend access to options for saving figures

---

neurodsp/sim/cycles.py
neurodsp/sim/transients.py
neurodsp/tests/sim/test_cycles.py
neurodsp/tests/sim/test_transients.py

This adds action potential cycles as the sum of two inverted asymmetrical gaussians:
```python
from neurodsp.sim.cycles import sim_ap_cycle
n_seconds = 1
fs = 1000
cycle_params = {'centers': (.25, .5), 'stds':(.15, .12),
'alphas':(4, .2), 'heights': (15, -5)}
cyc = sim_ap_cycle(n_seconds, fs, **cycle_params)
plt.plot(cyc)
```

[MRG] Simulate spikes / action potentials

---

neurodsp/plts/spectral.py

Before, `plot_power_spectra` only accepted 1d array or list of 1d array for freqs and powers. This adds support for 2d arrays. The requirement  to call `.tolist()` on a 2d power array for plotting to work felt strange - espcially since compute_spectrum returns 2d arrays for 2d inputs.
```python
from neurodsp.sim import sim_oscillation
from neurodsp.spectral import compute_spectrum
from neurodsp.plts import plot_power_spectra
n_seconds = 10
fs = 1000
freqs = [10, 20]
sigs = np.zeros((2, n_seconds * fs))
for ind, freq in enumerate(freqs):
sigs[ind] = sim_oscillation(n_seconds, fs, freq)
freqs, powers = compute_spectrum(sigs, fs)
plot_power_spectra([freqs, freqs], powers)
plot_power_spectra(np.array([freqs, freqs]), powers)
plot_power_spectra(freqs, [powers[0], powers[1]]) …
```

[ENH] Plot spectra accepts 2d arrays

---

neurodsp/filt/utils.py

Addresses #266. This is based on 
```python
inds = np.where(np.diff(np.logical_and(db > low, db < high)))[0]
```
returning an empty array. ~~I assumed when this is the case the transition bandwidth should be zero.~~
This now raises a value error stating the transition band is invalid, and suggests to redefine f_range.

[FIX] Error for invalid transition bandwidth

---

neurodsp/filt/filter.py
neurodsp/tests/filt/test_filter.py
neurodsp/utils/decorators.py

This allows 2d signals to be passed to filter_signal. My use case was filtering a 2d array of signals from a MEA.
I also updated np.stack to np.array in the decorator since it's equivalent in this case and 10x faster.
```python
%%timeit
out = [i+j for i in range(1000) for j in range(1000)]
out = np.stack(out)
```
> 1.27 s ± 10.6 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
```python
%%timeit
out = [i+j for i in range(1000) for j in range(1000)]
out = np.array(out)
```
> 98.9 ms ± 304 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)

[MRG] Add multidim decorator to filter_signal

---

neurodsp/burst/dualthresh.py

This is a small update that allow `min_n_cycles = 0` to be passed to detect_bursts_dual_threshold -  in case one doesn't want to remove detected bursts based on duration. Before this would raise an error.

[ENH] Allow min_n_cycles to be zero

---

neurodsp/sim/periodic.py

This fixes a small typo in the doctest, such that it would fail execution.
As a sidenote: one day we might poke at github actions, to get it to run doctests as well.

[BUG] - Fix doctest typo

---

neurodsp/plts/filt.py
neurodsp/plts/rhythm.py
neurodsp/plts/spectral.py
neurodsp/plts/time_series.py
neurodsp/plts/timefrequency.py

Our plot functions all have default sizes, which could be bypassed by passing in an Axis object. This extends the flexibility for controlling figure size, by allowing for passing in a `figsize` argument directly to each plot argument. 
In general, this `figsize` argument is caught by `kwargs`, and when creating a new axis, the figures will still default to the same size they always have, but this can now be over-written by the `figsize` input.

[MNT] - Allow for passing figsize to plots

---

neurodsp/plts/time_series.py
neurodsp/tests/plts/test_time_series.py

Responds to #291 
This update means one doesn't have to pass in a times vector to `plot_time_series`, and if not provided it will be plotted in terms of samples instead. 
@ryanhammonds - I like your idea of simply supporting `plot_time_series(None, sig)`, which is what this does. 
My initial idea had be to support `plot_time_series(sig)`, in which case the function would check that the second input is empty, infer the first input is the signal and proceed from there. It would be easy to add this, but this is where it makes the API a little messy. Do we want to add this additional shortcut, or should we keep it like this?
Note that due to how they wrap `plot_time_series`, this update makes this option available to `plot_instantaneous_measure` and `plot_bursts` as well.

[MNT] - Update plot_time_series to make times optional

---

neurodsp/filt/checks.py
neurodsp/sim/combined.py
neurodsp/sim/periodic.py
neurodsp/utils/checks.py

This is a fix for an annoying type-checking bug that can arise. 
Specifically, it started from `check_filter_definition`, which (on current main), will fail if given a numpy type number. 
Example - this fails unexpectedly (and unclearly):
`check_filter_definition('lowpass', np.int64(10))`
Note that this line is a shortcut to see the problem (not a likely function call), but this does can arise in more natural cases, such as using `np.arange`:
```
for f_val in np.arange(1, 10):
check_filter_definition('lowpass', f_val)
```
The cause of the bug is that we do type checks in line 70-83, which check for `int` or `float`, but a numpy number type doesn't get caught, the variables don't get assigned, and it all falls apart. So I added the type check of `np.number` here to fix it. 
I then updated …

[BUG] - Fix type-checking bug

---

doc/api.rst
neurodsp/sim/transients.py
neurodsp/tests/sim/test_transients.py

Responds to #262 - adds a simulation function to create an ERP complex, simulated as a decaying (damped) sine wave. 
@ryanhammonds: could you take a quick look at this - do you think it's something worth adding? It's a very simple approach for adding ERPs, but seems worth adding something like this. If it looks good to you, the main potential update is to update it to vary the start time (I wasn't immediately clear on how to do this).

[WIP/ENH] - Add erp sim func

---

doc/api.rst
neurodsp/sim/__init__.py
neurodsp/sim/combined.py
neurodsp/sim/utils.py
neurodsp/tests/sim/test_combined.py
neurodsp/tests/sim/test_utils.py
neurodsp/tests/utils/test_data.py
neurodsp/utils/data.py

Responds to #292 
Adds a function for applying amplitude modulation (`modulate_signal`) and a function to simulate amplitude modulated signals (`sim_modulated_signal`). 
Note that the original idea was to add `sim_modulated_oscillation`, but in the end, there is nothing really specific to applying amplitude modulation to an oscillatory signal, so this function might as well be more general. The only slight quirk, is that the only real place to put the general `sim_modulated_signal` is in the `combined` file - though it's not really a combined signal...
The modulate signal function applies amplitude modulation, and can be used like the following examples (note the two call signatures, allowing for a passing in a modulating signal, or a function name to create a modulating signal):
``` …
```

[ENH] - Add sim functions to creating amplitude modulated signals

---

neurodsp/aperiodic/dfa.py
neurodsp/sim/aperiodic.py
neurodsp/sim/combined.py
neurodsp/tests/aperiodic/test_dfa.py
neurodsp/tests/settings.py
neurodsp/tests/sim/test_aperiodic.py
neurodsp/tests/tutils.py

This PR does some refactors and tweaks of some of the newer simulation functions. 
An open question (nothing changed yet) is if we want to do any naming updates. 
- In particular, across the module we use both `exponent` (or `exp`), and now in these newer functions, `chi` to refer to the aperiodic exponent. I think I would vote we consolidate on using the term `exponent` consistently for this. The main counterpoint I can think of is that `exponent` is a pretty generic name, and in some cases it could be a little unclear. 
- While we're on the topic, I'm not 100% sold on `sim_peak_oscillation`, which seems to imply a slightly different thing from this being a "combined"  signal. I'm not sure I have a better suggestion though...
Thoughts?
For `sim_knee` and `sim_peak_oscillation`, there …

[MNT] - Simulations refactors

---

doc/api.rst
neurodsp/sim/periodic.py
neurodsp/tests/utils/test_data.py
neurodsp/utils/data.py

This PR is some minor clean-ups to using helper utilities in `sim/periodic`. The goal is to more consistently use helper utilities to make sure we are doing the same thing in the same ways. 
Updates:
- update to use `compute_nsamples` more consistently
- add a new helper function to compute the time length of a single cycle
- update to use `compute_cycle_nseconds` in simulation functions
Note for review: this should be a pretty straight forward update, I think, but given it changes some basic underlying estimations when simulating signals, it's probably worth keeping an eye on if this changes any sims in any unexpected ways (I haven't noticed anything so far).

[MNT] - Update utilities usage in sim/periodic

---

.github/workflows/build.yml
setup.py

This PR adds testing using Python version 3.10 to our continuous integration. 
Note: when I had a quick look for adding this, I saw some stuff about how writing "3.10" is required to enforce 3.10, otherwise it can end up with 3.1. I didn't check this, but seems to work, so I think this should be good.

[MNT] - Add CI testing against python 3.10

---

.github/workflows/build.yml
setup.py

Updates CI tests for:
- pinning the Ubuntu version, to maintain support of py3.6 (which fails on ubuntu-latest)
- updates the versions of the actions (which addresses future deprecations)
- adds testing and lists support for python 3.11

[MNT] - Update action version numbers

---

.gitignore
MANIFEST.in
Makefile
neurodsp/tests/settings.py
setup.py

Updates:
- use `build` for distributions (see https://github.com/fooof-tools/fooof/pull/282/)
- drop use of `package_resources` (see https://github.com/fooof-tools/fooof/pull/281)
This is matching the updates to fooof in the PRs above, so shouldn't need another much review other than to check that we're happy to apply these updates here as well
Also, @ryanhammonds - I made these updates to ByCycle, but screwed up my branching and accidentally pushed to main. The two last commits on ByCycle do the same as here (https://github.com/bycycle-tools/bycycle/commits/main) - if this is good with you, we're all good - but if you have any thoughts / comments, let me know and I can revert!

[MNT] - Build & install related updates

---

neurodsp/sim/aperiodic.py
neurodsp/sim/periodic.py
neurodsp/sim/transients.py

Quick check / update for some references. 
Most notably, updated 'Reference' -> 'References' in a docstring, as I happened to notice this typo leads to the section not appearing in the rendered docstring.

[MNT] - Fix typos

---

doc/api.rst
neurodsp/filt/utils.py
neurodsp/plts/__init__.py
neurodsp/plts/combined.py
neurodsp/plts/settings.py
neurodsp/plts/style.py
neurodsp/plts/time_series.py
neurodsp/tests/plts/test_combined.py
neurodsp/tests/plts/test_time_series.py

Some additions & tweaks to plotting including:
- add a plot for multiple time series (plotted with a vertical offset)
- add a combined 'timeseries & psd' plot
- style tweaks that allow for settings ticks and ticklabels through `plot_style`
- update styling descriptions and implementation, following fooof updates (https://github.com/fooof-tools/fooof/pull/300)
- add tight_layout as a custom plot style, meaning it can be passed in as an argument to turn on/off, and also apply with warning suppression, to stop annoying warnings that the plot layout has changed
The upshot of the style update is that something like this now works:
```
plot_function(data, xticks=[])
```
Note: the tests on newer versions of python were failing on a doctest, where an answer that used to come out at 2.0 is now …

[ENH] - Plot updates & extensions

---

doc/api.rst
neurodsp/spectral/power.py
neurodsp/tests/spectral/test_power.py
neurodsp/tests/timefrequency/test_hilbert.py
neurodsp/timefrequency/hilbert.py

Following from #322, in which `compute_spectrum` was used as a model for updating the 'wrapper' filter function, this PR takes the general approach that was expanded there and applies it back across other examples of using 'wrapper' functions in the module
Updates:
- Update `compute_spectrum` to have a more consistent API and use kwargs input checking
- Add a new 'wrapper' function for instantaneous measures

[MNT] - Update procedures for "wrapper" funcs

---

neurodsp/filt/filter.py
neurodsp/filt/fir.py
neurodsp/tests/filt/test_checks.py
neurodsp/tests/filt/test_filter.py
neurodsp/tests/filt/test_fir.py
neurodsp/tests/filt/test_utils.py

Responds to #321 
Previously, one could end up with an inconsistent set of input parameters to the general `filter_signal` function - for example, passing in `butterworth_order` without explicitly setting IIR `filter_type`. This update switches `filter_type` to default to None, an if not explicitly set, it is inferred from the given parameters, with additional updates to check that the given set of parameters are consistent.

[MNT] - Update filter type checks & inference

---

neurodsp/plts/settings.py
neurodsp/plts/utils.py
neurodsp/tests/plts/test_utils.py

Adds a plotting function utility for making a grid of axes.

[ENH] - Add a helper function for making multiple axis layout

---

doc/api.rst
neurodsp/spectral/__init__.py
neurodsp/spectral/checks.py
neurodsp/spectral/power.py
neurodsp/tests/spectral/test_power.py

This is an initial attempt at implementing a multi-taper method for estimating power spectral density. Refer to the issue raised [here](https://github.com/neurodsp-tools/neurodsp/issues/316) for more details.

[ENH] - Add multitaper method for spectral density estimation

---

neurodsp/spectral/checks.py
neurodsp/spectral/power.py
neurodsp/spectral/utils.py
neurodsp/tests/spectral/test_power.py
neurodsp/tests/spectral/test_utils.py

Adds ability to zeropad windows used in Welch's psd via a `npad` kwarg. This can result in smoother spectra. Working on timescales led me to think autoregressive PSD was a smoother method, but it really was the process of zero padding prior to taking the fft that lead to a smooth spectra. Similarily, zero padding the signal prior to fft is similar to zero padding either AR or ACF coefficients prior to fft'ing.
Here's an example using timescales (orange is a zeropadded welch's spectrum), but it also works for powerlaws.
```python
from neurodsp.spectral import compute_spectrum_welch
from neurodsp.sim import sim_synaptic_current
np.random.seed(0)
n_seconds = 5
fs = 1000
sig = sim_synaptic_current(n_seconds, fs, tau_d=0.01)
f, p = …
```

[ENH] Zero padding + Welch's PSD

---

neurodsp/filt/utils.py
neurodsp/tests/utils/test_outliers.py

The tests are currently failing as new numpy has deprecated np.NaN, which we use in a couple of our tests. This PR fixes that. Other than our use of these NaN values in our tests, I don't think this switch from numpy should affect anything else. 
In addition there is a minor update to a doctest example, to fix an error with doctest being very pedantic with type (float vs numpy float).

[MNT] - Fix use of nans in test for new numpy

---

neurodsp/plts/spectral.py

Currently, the default y-label for a PSD plot is the string literal 'Power (V^2/Hz)', which isn't properly formatted to display the superscript exponent. 
This PR updates the formatting, to actually use a superscript, so the plot label now looks like this:
I think the only thing to consider / check is whether there is some reason this formatting might not work across systems(?). It works smoothly for me - would be good if someone else could check it renders properly.

[MNT] - Fix power spectrum plot ylabel formatting

---

.github/workflows/build.yml
neurodsp/plts/timefrequency.py
setup.py

This PR responds to #340 - adding a colorbar option to our timefrequency plot. 
Because I messed up directing another PR, it also includes an update to add github action testing of Python 3.13, added in #342 but merged here instead of main (oops).

[ENH] - Add colorbar to time-frequency plot

---

neurodsp/timefrequency/wavelets.py

Addresses scipy deprecation of morlet, see #346.

add morlet from scipy

---

doc/api.rst
neurodsp/plts/__init__.py
neurodsp/plts/aperiodic.py
neurodsp/plts/spectral.py
neurodsp/plts/style.py
neurodsp/plts/time_series.py
neurodsp/plts/utils.py
neurodsp/tests/plts/test_aperiodic.py
neurodsp/tests/plts/test_spectral.py
neurodsp/tests/plts/test_utils.py
tutorials/aperiodic/plot_Autocorr.py

This PR updates and extends some plotting code. It adds to neurodsp some code I developed in the [AperiodicHistory](https://github.com/TomDonoghue/AperiodicHistory) project, which I think are general enough to be added her. 
Main updates:
- Create a new `prepare_multi_plot` which consolidates the same process we had in multiple places for supporting plots that may (or may not) have multiple inputs (e.g. plotting multiple spectra on the same plot)
- Adds a new `plot_autocorr` plot
- Adds a new `plot_spectra_3d` plot

[ENH] - Plotting updates

---

neurodsp/plts/rhythm.py
neurodsp/plts/spectral.py
neurodsp/rhythm/lc.py
neurodsp/sim/periodic.py
neurodsp/tests/sim/test_periodic.py

Follow up from #334, implementing new fix discussed there
In the original PR @ryanhammonds pointed out there is a bug with `sim_bursty_oscillation` no longer taking in a pre-defined burst array properly. There are some quirks to keeping the ordering (see #334), so this PR adds a new fix 
Updates:
- add an explicit test of burst_def as an array input
- update the type-checking of `burst_def` to not fail with an array input
- update examples to more properly use a consistent API for passing in burst params

[BUG] - Fix sim_bursty_oscillation for passing in burst_def array directly
