neurodsp/tests/test_timefreq.py, neurodsp/timefrequency.py
=> Allow for edge NaNs when applying timefrequency analysis

CONTRIBUTE.md
=> First draft of contribution guidelines

neurodsp/filt.py
=> bandstop filter error to warning

neurodsp/filt.py, neurodsp/tests/test_filt.py
=> Error when defining filter longer than signal

.gitignore, neurodsp/__init__.py, neurodsp/burst.py, neurodsp/filt.py, neurodsp/laggedcoherence.py, neurodsp/sim.py, neurodsp/spectral.py, neurodsp/swm.py, neurodsp/timefrequency.py, summary.sh
Some updates from a quick run-through with a linter, as well as some small doc updates. 
Updates:
- Cleans up imports: remove some unused, and re-order.
- Fix up some docstrings
- Linting fixes: line length, spacing, etc
- Small code refactorings, of things highlighted by linter
Notes:
- ToDo: fill in returns from `detect_bursts`
- In `detect_bursts` there is an input,  `filter_fn` that is never used. Is this a mistake?
- In burst, `_fit_slope` has an option to plot something - but matplotlib is never imported
- We could of course import matplotlib here - but perhaps plots can/should be defined in a separate file?
- in swm/_find_new_windowix, there is an input `L_samp` that is never used
I also added a 'summary' shell script that I usually have in my projects, to check things like this. …
=> Style & Doc Updates

neurodsp/__init__.py, neurodsp/burst.py, neurodsp/tests/test_burst.py
=> Clean bursting module

neurodsp/burst.py, neurodsp/timefrequency.py
issue #95
Also remove filter_fn inputs from remaining files
=> Add verbose option to timefrequency and burst detection functions

neurodsp/sim.py
=> Noninteger fs and n_seconds when simulating bursty oscillator

neurodsp/sim.py
=> Support simulating high frequency oscillations

doc/conf.py
=> Uncommented line to set the theme_path correctly.

doc/_templates/layout.html
This will set up google analytics when the site is built in the future. We can apply this to the current site by checking out a branch with the latest release tag (assuming that is where the current site was built from), cherry-picking the commit in this PR, and then running `make install` to push the changes.
=> [ENH] Google analytics

CONTRIBUTING.md, README.rst, doc/glossary.rst, examples/plot_mne_example.py, tutorials/burst/plot_BurstDetection.py, tutorials/filt/plot_Filtering.py, tutorials/rhythm/plot_LaggedCoherence.py, tutorials/rhythm/plot_SlidingWindowMatching.py, tutorials/sim/plot_SimulatePeriodic.py, tutorials/spectral/plot_SpectralPower.py, tutorials/spectral/plot_SpectralVariance.py, tutorials/timefreq/plot_InstantaneousMeasures.py
This one is just surface level text, only really needs a super quick sanity look over that I didn't like add any new typos or bad wording etc.
=> [FIX] Typos & small fixes in tutorials & documentation

neurodsp/aperiodic/irasa.py
Response to #224. This allows an array to be passed as hset.
=> [FIX] IRASA hset fix

CONTRIBUTING.md, README.rst
@ryanhammonds - I updated and standardized our Contributing file, here, and across {fooof, lisc, bycycle}. Can you have a a quick read through one of them, and let me know if anything seems weird? They're all ~ the same, so no need to full review each one. Thanks!
=> [DOC] - Update contributing doc

doc/api.rst, neurodsp/plts/__init__.py, neurodsp/plts/timefrequency.py, neurodsp/tests/plts/test_timefrequency.py, tutorials/timefreq/plot_MorletWavelet.py
This is a quick extension, adding a function for plotting time-frequency representations. 
Somewhat related to and inspired by / adapted from #226
=> [ENH] - Add a plot function for plotting time-frequency representations

doc/api.rst, neurodsp/aperiodic/__init__.py, neurodsp/filt/__init__.py, neurodsp/sim/__init__.py, neurodsp/utils/__init__.py
This updates to API list to include some new functions that have recently been added. 
It also:
- reorganizes the API list for the `aperiodic` sub-module
- adds an explicit listing of relevant utility functions
=> [DOC] - Update API list

neurodsp/aperiodic/dfa.py, neurodsp/aperiodic/irasa.py, neurodsp/burst/dualthresh.py, neurodsp/filt/filter.py, neurodsp/plts/time_series.py, neurodsp/sim/cycles.py, neurodsp/sim/info.py, neurodsp/sim/periodic.py, neurodsp/spectral/power.py, neurodsp/spectral/variance.py, neurodsp/tests/aperiodic/test_dfa.py, neurodsp/tests/aperiodic/test_irasa.py, neurodsp/tests/filt/test_checks.py, neurodsp/tests/filt/test_filter.py, neurodsp/tests/sim/test_cycles.py, neurodsp/tests/sim/test_periodic.py, neurodsp/timefrequency/wavelets.py, neurodsp/utils/core.py
This PR does a sweep of the tests, with some minor updates, including:
- mildly editing / adding / extending some tests
- fixing the `sim_asine_cycle` func for half cycles (that failed once tests were extended)
Also includes (other things done along the way):
- updating functions to use param checker functions 
- mild aesthetic updates of documentation
=> [MNT] - Tests updates

neurodsp/tests/timefrequency/test_hilbert.py
I'm using this PR to trigger GH actions and to figure out why 3.8/3.9 tests are failing.
=> [MRG] Fix Hilbert Test

neurodsp/plts/time_series.py
This is tiny doc thing that should have been in #295, but I forgot to push, so pushing this straight through now.
=> [MNT] - Plot time series: update docs for downstream effects

doc/api.rst, neurodsp/spectral/__init__.py, neurodsp/spectral/measures.py, neurodsp/tests/conftest.py, neurodsp/tests/spectral/test_measures.py, neurodsp/tests/utils/test_core.py, neurodsp/utils/core.py
These are some helper functions I find myself copying around and using in a few different places - so I figured that it might make sense to add them to NeuroDSP to have a stable / shared implementation. 
Added functions:
- `compute_absolute_power`
- `compute_relative_power`
- `compute_band_ratio`
Note: these are useful functions to compute these measures, especially for comparisons sake, but these are generally not measures I would _recommend_ (we might want to add some kind of disclaimer / note to these functions).
=> [ENH] - Add spectral measures

neurodsp/aperiodic/autocorr.py, neurodsp/aperiodic/dfa.py, neurodsp/aperiodic/irasa.py, neurodsp/sim/cycles.py, neurodsp/sim/periodic.py, neurodsp/sim/transients.py, neurodsp/spectral/measures.py, neurodsp/spectral/power.py, neurodsp/spectral/variance.py
This PR add some doctest examples to some functions that were missing them, and does some minor clean ups and additions to docstrings.
=> [MNT] - Docstring updates

neurodsp/spectral/__init__.py, tutorials/sim/plot_SimulateAperiodic.py, tutorials/sim/plot_SimulateCombined.py, tutorials/sim/plot_SimulateModulated.py, tutorials/sim/plot_SimulatePeriodic.py, tutorials/sim/plot_SimulateTransients.py
This PR add & extends tutorials related to additions for the 2.2 release.
=> [DOC] - Update Tutorials for 2.2

doc/api.rst, neurodsp/aperiodic/conversions.py, neurodsp/tests/aperiodic/test_conversions.py
This PR add conversion functions between different related aperiodic measures.
=> [ENH] - Add conversion functions for aperiodic measures

neurodsp/sim/aperiodic.py
Addresses #276. Before, the Poisson pop would default to a mean of 0 and variance of 1.
=> [FIX] Default mean and variance of poisson pop to 1

README.rst
This is a small update of the README related to changes for the upcoming 2.2 release. 
Note: WIP / could be amended further as we finish up the release.
=> [MNT] - README updates for 2.2

doc/api.rst, neurodsp/plts/__init__.py, neurodsp/plts/combined.py, neurodsp/tests/plts/test_combined.py
This is a minor update to the multi plot, to allow it to support an input of multiple time series, using `plot_multi_time_series` if so.
=> [WIP] - Update plot_multi to support multiple timeseries
